stages:
  - prepare
  - docker-build
  - docker-publish
  
Prepare:
  stage: prepare
  script:
    - echo "hello world"
    - sleep 1 && echo "Prepare OK "
    - whoami
  tags: 
    - sap
  
Build:
  stage: docker-build
  # before_script:
  #   - export HTTP_PROXY="http://cmsproxy.npr.nornick.ru:18080"
  #   - export HTTPS_PROXY="http://cmsproxy.npr.nornick.ru:18080"
  script:
    - docker build  -t nexus.npr.nornick.ru/datalake/cases/sap/app/${CI_PROJECT_NAME} .
  tags: 
    - sap

  
Publish:
  stage: docker-publish
  script:
    - whoami
    - docker push nexus.npr.nornick.ru/datalake/cases/sap/app/${CI_PROJECT_NAME}
  tags: 
    - sap
