# column_mapping.py
# Маппинг: Excel → БД и обратно

COLUMN_MAPPING = {
    'Дата': 'date',
    'Fact': 'fact',
    'predict_naive': 'predict_naive',
    'predict_autoARIMA': 'predict_autoarima',
    'predict_TFT': 'predict_tft',
    'predict_PatchTST': 'predict_patchtst',
    'predict_Chronos_base': 'predict_chronos_base',
    'predict_TS_ML': 'predict_ts_ml',
    'predict_svm6': 'predict_svm6',
    'predict_svm9': 'predict_svm9',
    'predict_svm12': 'predict_svm12',
    'predict_linreg6_with_bias': 'predict_linreg6_with_bias',
    'predict_linreg9_with_bias': 'predict_linreg9_with_bias',
    'predict_linreg12_with_bias': 'predict_linreg12_with_bias',
    'predict_linreg6_no_bias': 'predict_linreg6_no_bias',
    'predict_linreg9_no_bias': 'predict_linreg9_no_bias',
    'predict_linreg12_no_bias': 'predict_linreg12_no_bias',
    'predict_stacking_RFR': 'predict_stacking_rfr',
    'predict_naive разница': 'predict_naive_diff',
    'predict_autoARIMA разница': 'predict_autoarima_diff',
    'predict_TFT разница': 'predict_tft_diff',
    'predict_PatchTST разница': 'predict_patchtst_diff',
    'predict_Chronos_base разница': 'predict_chronos_base_diff',
    'predict_TS_ML разница': 'predict_ts_ml_diff',
    'predict_svm6 разница': 'predict_svm6_diff',
    'predict_svm9 разница': 'predict_svm9_diff',
    'predict_svm12 разница': 'predict_svm12_diff',
    'predict_linreg6_with_bias разница': 'predict_linreg6_with_bias_diff',
    'predict_linreg9_with_bias разница': 'predict_linreg9_with_bias_diff',
    'predict_linreg12_with_bias разница': 'predict_linreg12_with_bias_diff',
    'predict_linreg6_no_bias разница': 'predict_linreg6_no_bias_diff',
    'predict_linreg9_no_bias разница': 'predict_linreg9_no_bias_diff',
    'predict_linreg12_no_bias разница': 'predict_linreg12_no_bias_diff',
    'predict_stacking_RFR разница': 'predict_stacking_rfr_diff',
    'predict_naive отклонение  %': 'predict_naive_pct',
    'predict_autoARIMA отклонение  %': 'predict_autoarima_pct',
    'predict_TFT отклонение  %': 'predict_tft_pct',
    'predict_PatchTST отклонение  %': 'predict_patchtst_pct',
    'predict_Chronos_base отклонение  %': 'predict_chronos_base_pct',
    'predict_TS_ML отклонение  %': 'predict_ts_ml_pct',
    'predict_svm6 отклонение  %': 'predict_svm6_pct',
    'predict_svm9 отклонение  %': 'predict_svm9_pct',
    'predict_svm12 отклонение  %': 'predict_svm12_pct',
    'predict_linreg6_with_bias отклонение  %': 'predict_linreg6_with_bias_pct',
    'predict_linreg9_with_bias отклонение  %': 'predict_linreg9_with_bias_pct',
    'predict_linreg12_with_bias отклонение  %': 'predict_linreg12_with_bias_pct',
    'predict_linreg6_no_bias отклонение  %': 'predict_linreg6_no_bias_pct',
    'predict_linreg9_no_bias отклонение  %': 'predict_linreg9_no_bias_pct',
    'predict_linreg12_no_bias отклонение  %': 'predict_linreg12_no_bias_pct',
    'predict_stacking_RFR отклонение  %': 'predict_stacking_rfr_pct',
    'Статья': 'article',
    'pipeline': 'pipeline',
    # Для листа Tabular_ensemble_models_info
    'Ансамбль': 'ensemble',

    # Для листа Tabular_feature_importance
    'feature': 'feature',
    'importance': 'importance',
    'stddev': 'stddev',
    'p_value': 'p_value',
    'n': 'n',
    'p99_high': 'p99_high',
    'p99_low': 'p99_low',
    # Дата и Статья уже есть
    
    # Для корректировок
    'Корректировка, руб': 'adjustments',
}

# Обратный маппинг: БД → Excel
REVERSE_COLUMN_MAPPING = {v: k for k, v in COLUMN_MAPPING.items()}
