Статья:
  Торговая ДЗ:
    - Готовая продукция
    - Авансы полученные(металлы)   # USD
  
  Прочая ДЗ:
    - Материалы
  
  Авансы выданные и расходы будущих периодов:
    - Материалы
    - Прочие налоги к возмещению ST  # lag2
    - Прочие налоговые обязательства  # lag2
  
  Прочие налоги к возмещению ST:
    - Материалы
    - Готовая продукция
    - Прочие налоговые обязательства
    - НЗП
    - Торговая КЗ
  
  Прочие налоговые обязательства:
    - Готовая продукция
    - Прочая ДЗ
    - Материалы
    - Задолженность перед персоналом
    - НЗП
    - Торговая КЗ
  
  Задолженность перед персоналом:
    - Краткосрочный резерв по премиям
    - Резерв по неиспользованным отпускам
  
  Резерв по неиспользованным отпускам:
    - Краткосрочный резерв по премиям
    - Задолженность перед персоналом
  
  Краткосрочный резерв по премиям:
    - Задолженность перед персоналом
    - Резерв по неиспользованным отпускам
  
  Прочее:
    - Краткосрочный резерв по премиям
    - Задолженность перед персоналом
  
  Кредиторская задлолженность по ОС:
    - Курс
  
  Авансы полученные:
    - Материалы
  
  Авансы полученные(металлы):
    - Готовая продукция
    - Торговая ДЗ
  
  Торговая КЗ:
    - Авансы выданные и расходы будущих периодов
    - Материалы
    - Авансовые платежи по налогу на прибыль
    - Прочие налоги к возмещению ST
    - Прочие налоговые обязательства

  Авансовые платежи по налогу на прибыль: []

  Обязательства по налогу на прибыль: []

  ЧОК (нормализовано на расчеты с акционерами):
    - Торговая ДЗ
    - Прочая ДЗ
    - Авансы выданные и расходы будущих периодов
    - Прочие налоги к возмещению ST
    - Прочие налоговые обязательства
    - Задолженность перед персоналом
    - Резерв по неиспользованным отпускам
    - Краткосрочный резерв по премиям
    - Прочее
    - Кредиторская задлолженность по ОС
    - Авансы полученные
    - Авансы полученные(металлы)
    - Торговая КЗ
    - Авансовые платежи по налогу на прибыль
    - Обязательства по налогу на прибыль
    - Курс


Фичи в Статьях для LAG:
  Авансовые платежи по налогу на прибыль:
    Авансовые платежи по налогу на прибыль: 1
  Обязательства по налогу на прибыль:
    Обязательства по налогу на прибыль: 1
  Авансы выданные и расходы будущих периодов:
    Прочие налоги к возмещению ST: 2
    Прочие налоговые обязательства: 2

Фичи в Статьях для USD:
  Торговая ДЗ:
    - Авансы полученные(металлы)
    
Статьи для предикта в USD:
  - Торговая ДЗ

Статьи для раскладывания даты на месяц и год:
  - Авансовые платежи по налогу на прибыль
  - Обязательства по налогу на прибыль


DATE_COLUMN: Дата
RATE_COLUMN: Курс
item_id: INDIVIDUAL
factor: INDIVIDUAL
metric_for_training: MAE
PREDICT_BASE: True
PREDICT_BASEplus: False

models_to_use:
  NaiveModel: {}
TABPFNMIX_model:
  TABPFNMIX:
    model_path_regressor: 'pretrained_models/tabpfn-mix-1.0-regressor'
    n_ensembles: 1
    max_epochs: 30
